In [29]:
import numpy as np

In [30]:
def gradiente(f, xk):
    n=xk.size
    eps=10e-8
    res = np.zeros(n)
    x0 = np.array(xk)
    xh = np.array(xk)
    for i in range(n):
        xh[i] += eps
        res[i] = (f(xh)-f(x0))/eps
        xh[i] -= eps
    return res

In [31]:
def hessiana(f, xk):
    n = xk.size
    eps = 10e-8
    res = np.zeros([n,n])
    for i in range(n):
        xh = np.array(xk)
        xh[i] += eps
        gx0 = np.array(gradiente(f,xk), dtype=float)
        gxh = np.array(gradiente(f,xh), dtype=float)
        res[:,i] = (gxh - gx0)/eps
    return res

In [32]:
def condiciones_optimalidad(f, xk):
    if all(i<10e-3 for i in gradiente(f,xk)) and all(j>-10e-3 for j in np.linalg.eigvalsh(hessiana(f,xk))):
        return True
    else:
        return False       

In [45]:
def mk(f, xk, p):
    H = hessiana(f, xk)
    G = gradiente(f, xk).T
    return f(xk) + np.dot(p.T,G) + np.dot(np.dot(p.T,H),p)/2


In [46]:
#Ejemplo 1
def f(xk):
    return 3*xk[0]**2 + 2*xk[1]**4 - 6*xk[2]**3-4;
xk = np.array([4,2,5], dtype=float)
p = np.array([3,10,2],dtype = float).T

print("Gradiente: \n", gradiente(f,xk))
print("Hessiana: \n", hessiana(f, xk))
print("¿Es Optimo? \n", condiciones_optimalidad(f,xk))
print("MK: \n", mk(f, xk, p))

Gradiente: 
 [  24.00000085   64.0000053  -450.00001023]
Hessiana: 
 [[   0.          -11.36868377    0.        ]
 [ -11.36868377   79.58078641  -11.36868377]
 [ -11.36868377  -11.36868377 -181.89894035]]
¿Es Optimo? 
 False
MK: 
 2150.701234658278


In [40]:
#Ejemplo 2
def f(xk):
    return 100*(xk[1]-xk[0]**2)**2+(1-xk[0])**2
xk = np.array([1,1],dtype=float)
p = np.array([10,2], dtype=float).T

print("Gradiente: \n", gradiente(f,xk))
print("Hessiana: \n", hessiana(f, xk))
print("¿Es Optimo? \n", condiciones_optimalidad(f,xk))
print("MK: \n", mk(f, xk, p))

Gradiente: 
 [4.0100004e-05 1.0000000e-05]
Hessiana: 
 [[ 802.00024074 -400.00002045]
 [-400.00002045  200.00000023]]
¿Es Optimo? 
 True
MK: 
 32500.012049680507
