# Guia de Python

Creador: David Martín del Campo Vergara.

Contacto: david.mcv97@gmail.com

Guía intuitiva e interactiva del uso de Python en Jupyter.

## Operaciones básicas

### ayuda

In [ ]:
file import gradentie 

In [1]:
bool?

### declaración de variables

In [2]:
x,y = 3,4.1

### imprimir

In [3]:
print ("el valor de x es",x)
print ("el valor de y es")
y

el valor de x es 3
el valor de y es


4.1

### suma

In [4]:
x + y

7.1

### resta

In [5]:
x-y

-1.0999999999999996

### multiplicación

In [6]:
x*y

12.299999999999999

### división

In [7]:
x/y

0.7317073170731708

### potencias

In [8]:
x**y

90.40597709674623

### modulo (natural y real)

In [9]:
x%y

3.0

### numeros complejos

In [10]:
z = 2 + 3j
z

(2+3j)

### transformar un numero a texto

In [11]:
str(2.3)

'2.3'

### concatenación de texto

In [12]:
"hola," + " te quiero " + str(1000)

'hola, te quiero 1000'

In [13]:
3 * "hola "

'hola hola hola '

### funciones recursivas

In [14]:
x = 1
print (x)

1


In [15]:
x += 1 
print (x)

2


In [16]:
x /= 2
print (x)

1.0


In [17]:
x *= 2
print (x)

2.0


In [18]:
x %= 1.5
print (x)

0.5


### logicos

In [19]:
3 == 3

True

In [20]:
3 != 3

False

In [21]:
3 < 0 or 0 < 3

True

In [22]:
3 < 0 and 3 > 0 

False

### condicional if

In [23]:
x = 1
if x > 3:
    print ("x mayor a 3")
elif x == 3: 
    print ("x igual a 3")
else:
    print ("x menor a 3")

x menor a 3


### Condicional while

In [24]:
x = 0
while x < 10:
    x = x+1
    break
print(x)

1


# Tipos de elementos

In [25]:
type(False)

bool

In [26]:
type(1)

int

In [27]:
type(0.3)

float

In [28]:
type(1+1j)

complex

In [29]:
type('hola')

str

### listas: conjunto ordenado de elementos

In [30]:
x = [1,2,3,4,5]
type(x)

list

In [31]:
x[0]

1

In [32]:
x[1:4]

[2, 3, 4]

In [33]:
x[-1]

5

In [34]:
x.append(6)
x[5]

6

In [35]:
x.pop(0)
x

[2, 3, 4, 5, 6]

In [36]:
x.remove(6)
x

[2, 3, 4, 5]

In [37]:
empty = []
print (empty)

[]


### tuplas: estructura de elementos no modificable

In [38]:
x = (1,2)
type(x)

tuple

In [39]:
x[0] = 1

TypeError: 'tuple' object does not support item assignment

###  conjuntos

In [40]:
x = {1,2}
type(x)

set

### diccionarios: parejas de elementos con la forma "llave:elemento"

In [41]:
x = {1:'a',2:'b'}
type(x)

dict

In [42]:
x.keys()

dict_keys([1, 2])

In [43]:
x.values()

dict_values(['a', 'b'])

In [44]:
x.items()

dict_items([(1, 'a'), (2, 'b')])

In [45]:
x[1]

'a'

In [46]:
x[3]='c'
x[4]='d'
print(x)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


In [47]:
del x[3]
x.pop(4)
print(x)

{1: 'a', 2: 'b'}


### for lógico

In [48]:
for x in [1,2,3]:
    print (x)

1
2
3


### Rango: naturales ordenados

In [49]:
for x in range(2):
    print (x)

0
1


In [50]:
for x in range(-2,2):
    print (x)

-2
-1
0
1


In [51]:
for x in range(-6,5,2):
    print(x)

-6
-4
-2
0
2
4


# Funciones

In [52]:
from math import sqrt, atan, acos, pi
def car_esf(x,y,z):
    """
    Esta funcion transforma coordenadas cartesianas en R3 a coordenadas esféricas.
        entrada: x,y,z coordenada cartesiana en R3.
        salida: a1,a2,r coordenada esférica en R3.
    a1 es el angulo horizontal, a2 es el aúngulo vertical, r es el radio.
    """
    if x != 0:
        a1 = atan(y/x)
    else:
        a1 = pi/2
    r = sqrt(x*x + y*y + z*z)
    if r != 0:
        a2 = acos(z/r)
    else:
        a1 = 0
        a2 = 0
    return a1,a2,r

In [53]:
car_esf?

In [54]:
car_esf??

In [55]:
car_esf(1,2,3)

(1.1071487177940904, 0.6405223126794245, 3.7416573867739413)

### Python Interactivo

In [56]:
from ipywidgets import interact

In [57]:
interact(car_esf, x=10, y = 10, z = 10)

interactive(children=(IntSlider(value=10, description='x', max=30, min=-10), IntSlider(value=10, description='…

<function __main__.car_esf(x, y, z)>

### funciones lambda

funciones pequeñas y anonimas, es decir que se guardan sin identificador

In [4]:
f = lambda x,y : x + y  # las variables declaradas son x,y
f(2,3)

5

# Numpy

Numpy es una librería de python para computación cientifica. En otras palablas, mates mamalonas

In [58]:
import numpy as np #el 'as' nos da un shortcut de la libreria.  

### Arrays

Archivos característicos de Numpy, toman el papel de vectores. son como listas pero con menos propiedades y, por lo tanto, más rapidas

In [59]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [61]:
y = np.arange(3,8)
y

array([3, 4, 5, 6, 7])

In [62]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [63]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
z =np.zeros((2,2,2)) #genera un cubo de ceros
z

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [65]:
a = np.linspace(0,1,11)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [66]:
b = np.ones(3)
b

array([1., 1., 1.])

In [67]:
c = np.empty((2,2)) #no es cero, pero sus entradas son menores al epsilon de maquina
c

array([[4.68847663e-310, 0.00000000e+000],
       [5.43705311e-143, 1.50008929e+248]])

In [68]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Slicing

en numpy podemos tomar parte de un vector usando el siguiente comando

In [120]:
vector = np.array([2,4,6,8,10])
vector

array([ 2,  4,  6,  8, 10])

In [121]:
sub_vector = vector[1:4] #recordemos que en python la primera posición es 0b

a esto se le llama slicing, y tiene una función especial. a pesar de que el vector original y el vector "rebanado" tienen diferentes nombres, ambos mantienen los mismos valores. Es decir, si alteramos el vector original, alteraremos el rebanado, y viceversa

In [122]:
sub_vector[0] = 0 #aqui cambiamos el vector rebanado
sub_vector

array([0, 6, 8])

In [123]:
vector #veamos como este también cambio

array([ 2,  0,  6,  8, 10])

In [124]:
vector[2] = 0 #ahora cambiamos el vector original
vector

array([ 2,  0,  0,  8, 10])

In [125]:
sub_vector # y el vector rebanado cambia

array([0, 0, 8])

### tipo de dato

In [69]:
x.dtype

dtype('int64')

esto quiere decir que x es un dato de numpy del tipo entero (int) guardado en 64 bits.

In [70]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [71]:
z = z.astype(int)
z

array([0, 0, 0])

In [72]:
z.ndim #dimension

1

In [73]:
z.shape #tamaño de cada eje de la matriz

(3,)

In [74]:
z = np.ones((3,3)).astype(np.int32)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [75]:
z.ndim

2

Notemos que cada Array solo puede contener un solo tipo de datos

### transformaciones de vectores y matrices

en numpy podemos transformar vectores en matrices y viceversa de una forma ordenada 

In [76]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [77]:
a = a.reshape((2,2)) #transforma el vector en una matriz de 2 x 2
a

array([[0, 1],
       [2, 3]])

In [78]:
a = a. reshape(4) #lo vuelve a hacer en un vector de 1 x 4 
a

array([0, 1, 2, 3])

In [79]:
b = np.arange(8) #veamos otro ejemplo
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
b = b.reshape((2,2,2)) #ahora vuelve el vector en una matriz
b

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
b = b.ravel() # ravel es otra forma de aplanar una matriz en un vector ordenadamente
b

array([0, 1, 2, 3, 4, 5, 6, 7])

### transposicion de matrices en R^n

In [101]:
a = np.array([[1,1],[0,0]])
a

array([[1, 1],
       [0, 0]])

In [102]:
a.T

array([[1, 0],
       [1, 0]])

### Broadcasting

Broadcasting se refiere a los comandos para arrays de numpy que realizan una operacion casilla por casilla

In [164]:
x = np.arange(5)
y = np.random.rand(5) #generador de uniformes (0,1)
print(x,y)

[0 1 2 3 4] [0.37897034 0.51077283 0.46476133 0.39316457 0.77680978]


In [165]:
x = x + 1 
x

array([1, 2, 3, 4, 5])

In [166]:
x = x**2
x

array([ 1,  4,  9, 16, 25])

In [167]:
x = x*-1
x

array([ -1,  -4,  -9, -16, -25])

In [168]:
x =np.abs(x) #valor absoluto
x

array([ 1,  4,  9, 16, 25])

In [169]:
x = np.sqrt(x)
x

array([1., 2., 3., 4., 5.])

In [170]:
x = np.sign(x)
x

array([1., 1., 1., 1., 1.])

In [171]:
np.isfinite(x)

array([ True,  True,  True,  True,  True])

In [172]:
np.logical_not(x) #devuelve True sii la entrada es cero

array([False, False, False, False, False])

In [173]:
np.ceil(y) #funcion techo

array([1., 1., 1., 1., 1.])

In [174]:
np.floor(y) #funcion piso

array([0., 0., 0., 0., 0.])

In [175]:
np.rint(y) #devuelve el entero más cercano

array([0., 1., 0., 0., 1.])

In [177]:
np.add(x,y)

array([1.37897034, 1.51077283, 1.46476133, 1.39316457, 1.77680978])

In [179]:
np.multiply(x,y)

array([0.37897034, 0.51077283, 0.46476133, 0.39316457, 0.77680978])

In [181]:
np.maximum(x,y) #compara entrada contra entrada y devuelve el máximo

array([1., 1., 1., 1., 1.])

In [183]:
np.minimum(x,y)

array([0.37897034, 0.51077283, 0.46476133, 0.39316457, 0.77680978])

In [185]:
np.logical_and(x,y) # devuelve true sii la entrada de X y Y es distinta de cerob

array([ True,  True,  True,  True,  True])

In [187]:
x.sum() #suma todas las entradas

5.0

In [192]:
y.mean() #media poblacional

0.5048957690000504

In [194]:
y.cumsum() #suma acumulada por entrada

array([0.37897034, 0.88974317, 1.3545045 , 1.74766907, 2.52447885])

In [196]:
y.cumprod() #producto acumulado

array([0.37897034, 0.19356775, 0.08996281, 0.03537019, 0.02747591])

In [198]:
y > 0.5

array([False,  True, False, False,  True])

In [200]:
(y > 0.5).sum() #puede sumar logicos, tomando true = 1

2