In [2]:
import numpy as np

In [3]:
lst = [1, 2, 3, 4, 5]
lst
#Se utilizan las listas por la versatilidad

[1, 2, 3, 4, 5]

In [4]:
arr = np.array([1, 2, 3, 4, 5]) #Arreglo
arr
#Se utilizan los arreglos por la velocidad

array([1, 2, 3, 4, 5])

In [5]:
lst[2:3]

[3]

In [6]:
arr[2:3] #Elementos de la posicion n+1 a k [n:k]

array([3])

In [7]:
lst[-1] = "Las listas pueden tener varios tipos de datos" 
#Sustituye el elemento de la ultima posicion
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [8]:
arr[-1] = "Los arreglos no ..."
#No se pueden mexclar los tipos de datos en los arreglos
#Va a intentar castear el tipo de dato, pero no siempre se puede convertir.
#Por ejemplo, los tectos no se pueden castear a numeros

ValueError: invalid literal for int() with base 10: 'Los arreglos no ...'

In [9]:
arr.dtype #Saber el tipo de datos que tiene el arreglo

dtype('int64')

In [10]:
arr[-1] = 1.23234
arr
#Como tenemos que el tipo de dato son los enteros, entonces el
#numero real lo castea a entero, por eso es 1

array([1, 2, 3, 4, 1])

In [11]:
arr.dtype

dtype('int64')

In [12]:
adoring_bootharr = np.arange(1e7)
#Arreglo de un millon de elementos
#Se crea de cero a 1e7 

In [13]:
lst = arr.tolist() 
#Se cambia el arreglo a lista

In [18]:
#Se multiplica la lista por una constante
#Los arreglos, sin necesidad de una funcion, se pueden multiplicar por constantes
def lst_multiplicacion(alist, scalar):
    for i, val in enumerate (alist):
        alist[i] = val * scalar
    return alist

In [19]:
%timeit arr * 1.1 #El tiempo que tarda

5.53 µs ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%timeit lst_multiplicacion(lst, 1.1)

1.96 µs ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Creacion de arreglos

In [21]:
#Crea un arreglo a partir de una lsita
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 1])

In [22]:
#Arreglo desde el 10 al 20
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
#Arreglo de ceros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [24]:
#Arreglo entre el 0 y el 1, con 100 elementos
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [26]:
#Arreglo con numeros del 0 al 1, con 100 elementos. 
#Tiene una escala logaritmica base 10
arr = np.logspace(0,1,100, base = 10)
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [27]:
#Arreglo de dos dimensiones o mas
arr2d = np.zeros((5,5))
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
#La matriz de ceros se castea a entero y luego se le suma 1 a cada entrada 
cubo = np.zeros((5,5,5)).astype(int) + 1
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [29]:
cubo = np.ones((5,5,5)).astype(np.float16)
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [30]:
#Tipo de dato del arreglo 
cubo.dtype

dtype('float16')

In [31]:
#Da valores muy pequeños, los podríamos denominar como epsilom
np.empty((2,3,4))

array([[[4.65327099e-310, 0.00000000e+000, 4.65326997e-310,
         4.65326997e-310],
        [4.65326997e-310, 4.65326997e-310, 4.65326997e-310,
         4.65326997e-310],
        [4.65326997e-310, 4.65326997e-310, 4.65326997e-310,
         4.65326997e-310]],

       [[4.65326997e-310, 4.65326997e-310, 4.65326997e-310,
         4.65326997e-310],
        [4.65326997e-310, 4.65326997e-310, 4.65326997e-310,
         4.65326997e-310],
        [4.65326997e-310, 4.65326997e-310, 4.65326997e-310,
         4.65326997e-310]]])

In [32]:
#Matriz identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
#Numeros aleatrios
np.random.rand(3)

array([0.45835522, 0.18859977, 0.3253555 ])

### Reshaping  

In [35]:
arr = np.arange(1000)

In [36]:
#Modifica el arreglo en bloques de 10 x 10 x 10
#Se le puede cambiar la dimension
arr3d = arr.reshape((10,10,10))

In [37]:
arr3d.ndim

3

In [38]:
arr3d.shape

(10, 10, 10)

In [39]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [41]:
arr = np.arange(200)

In [42]:
arr2d = arr.reshape((10,20))

In [43]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

### Aplanar

In [44]:
arr = np.zeros((4, 4, 4, 4))

In [45]:
arr.shape

(4, 4, 4, 4)

In [47]:
#Cambia todo a una sola dimension 
arr_plano = arr.ravel()

In [48]:
arr_plano.shape

(256,)

### Broadcasting - Hacer una operacion para todos los elementos dentro del arreglo

In [49]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [50]:
data + 1

array([2, 3, 4, 5, 6])

In [51]:
data * 2

array([ 2,  4,  6,  8, 10])

In [52]:
data ** 2

array([ 1,  4,  9, 16, 25])

### Transponer

In [54]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
#Transpone la matriz
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [56]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [57]:
#Transpone en varias dimensiones
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

### Slicing e indexado

In [58]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
#El slice es un pedazo de la lista
#Si se cambia el slice, el arreglo original tambien se cambia
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [60]:
arr_slice[1] = 12345678

In [61]:
arr_slice

array([       5, 12345678,        7])

In [62]:
arr

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [63]:
arr_slice[:] = 345

In [64]:
arr_slice

array([345, 345, 345])

In [65]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [66]:
#Copia del arreglo
arr2 = np.copy(arr)
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [67]:
arr2[5:8] = [5,6,7]
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [69]:
np.may_share_memory(arr, arr_slice)

True

In [70]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [71]:
arr = np.arange(9)

In [72]:
arr.shape = (3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
arr.ndim

2

In [74]:
#Las posiciones se cuentan desde el cero
arr[2]

array([6, 7, 8])

In [75]:
arr[-1]

array([6, 7, 8])

In [76]:
arr[1][1]

4

In [77]:
#Del primero a que acabe
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [78]:
#De la posicion dos hacia atras
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
arr[:1,:2]

array([[0, 1]])

In [80]:
arr[1:, :2]

array([[3, 4],
       [6, 7]])

In [81]:
arr[1,]

array([3, 4, 5])

In [82]:
arr[1,:2]

array([3, 4])

In [83]:
arr[1,2:]

array([5])

In [84]:
arr[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [85]:
arr[:,:1]

array([[0],
       [3],
       [6]])

In [86]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
#Nos dice que entradas son mayores a dos
index = arr > 2

In [88]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [89]:
#Crea un arreglo con los valores verdaderos 
arr[index]

array([3, 4, 5, 6, 7, 8])

In [90]:
arr2 = arr[index]

In [91]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
arr2

array([3, 4, 5, 6, 7, 8])

In [93]:
arr = np.ones((5,4))

In [94]:
for i in range(5):
    arr[i] = i

In [95]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [97]:
#Acomoda las filas
arr[[4,3,1,2]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [98]:
arr[[-3,-2,-1]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

### Funciones universales - realizan operaciones elemento por elemento en los arreglos

In [99]:
arr = np.arange(10)

In [103]:
arr = -1*arr
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [104]:
arr = np.abs(arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [107]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [108]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [109]:
#El if de un numero es cierto, excepto si es 0
#Por lo que la negacion es que el 0 es verdadero y los demas falso
np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [110]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
arr = np.random.randn(10)
arr

array([-2.06663911, -0.49385626, -0.09360368, -0.34035626,  0.13488507,
       -0.1218958 ,  0.05514821, -0.54934435,  0.7682149 , -0.67826384])

In [112]:
np.ceil(arr)

array([-2., -0., -0., -0.,  1., -0.,  1., -0.,  1., -0.])

In [113]:
np.floor(arr)

array([-3., -1., -1., -1.,  0., -1.,  0., -1.,  0., -1.])

In [114]:
#Redondeo del entero más cercano
np.rint(arr)

array([-2., -0., -0., -0.,  0., -0.,  0., -1.,  1., -1.])

In [115]:
arr2 = np.ones(10)

In [116]:
np.add(arr, arr2)

array([-1.06663911,  0.50614374,  0.90639632,  0.65964374,  1.13488507,
        0.8781042 ,  1.05514821,  0.45065565,  1.7682149 ,  0.32173616])

In [117]:
#Se multiplica entrada por entrada
np.multiply(arr, arr2)

array([-2.06663911, -0.49385626, -0.09360368, -0.34035626,  0.13488507,
       -0.1218958 ,  0.05514821, -0.54934435,  0.7682149 , -0.67826384])

In [118]:
np.maximum(arr, arr2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### Agregaciones

In [120]:
arr

array([-2.06663911, -0.49385626, -0.09360368, -0.34035626,  0.13488507,
       -0.1218958 ,  0.05514821, -0.54934435,  0.7682149 , -0.67826384])

In [121]:
arr.sum()

-3.3857111152106985

In [122]:
#Media del arreglo
arr.mean()

-0.33857111152106983

In [123]:
arr = np.random.randn(5,4)
arr

array([[ 1.0286254 , -0.71334019,  0.11872551, -0.51421076],
       [-0.00567603, -2.21957498, -1.93097571,  0.50203003],
       [ 2.56524193, -0.79462499, -1.62975612, -1.45988102],
       [-0.57418279, -0.98741515, -0.15514438,  0.55993725],
       [ 0.37204921, -0.78904794, -0.91971897, -0.35689688]])

In [124]:
arr.sum()

-7.903836578757749

In [125]:
arr.mean()

-0.39519182893788746

In [126]:
#Suma solo un renglon o columna
#Si es cero es horizontal y si es 1 es vertical
arr.sum(0)

array([ 3.38605773, -5.50400324, -4.51686967, -1.2690214 ])

In [127]:
arr = np.arange(10)

In [128]:
#suma acumulada
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [129]:
#Producto acumulado
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [130]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [132]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [133]:
#Suma la cantidad de verdaderos
(arr > 5).sum()

4

### Operaciones de conjuntos

In [134]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [136]:
np.unique(arr2)

array([1.])

In [137]:
np.intersect1d(arr, arr2)

array([1.])

### Casting - El tipo de mayor jerarquia define el cast

In [138]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [139]:
a + 1.5 #La asignacion no cambia el tipo de arreglo

array([2.5, 3.5, 4.5])

In [140]:
a.dtype

dtype('int64')

In [141]:
(a + 1.5).dtype

dtype('float64')

### Tipos de numeros

In [143]:
#El maximo numero que podemos tener
np.iinfo(np.int32).max, 2 ** 31 + 1

(2147483647, 2147483649)

In [144]:
np.finfo(np.float64).max

1.7976931348623157e+308

In [145]:
np.finfo(np.float64).eps

2.220446049250313e-16

In [146]:
np.float32(1e-8) + np.float32(1) == 1

True

In [147]:
np.float64(1e-8) + np.float64(1) == 1

False

### Estructura de datos

In [149]:
muestra = np.zeros((6,), dtype = [('codigo' , 'S4'), ('posicion' , float), ('valor', float)])
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [150]:
muestra.ndim

1

In [151]:
muestra.shape

(6,)

In [153]:
#Lo que debe de tener cada una de las entradas
#Cada entrada va a tener un codigo, una posicion y un valor
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [154]:
muestra[:] = [('ALFA', 1, 0.37), ('BETA', 1, 0.11), ('TAU', 1, 0.13), ('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [155]:
muestra.shape

(6,)

In [156]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [157]:
muestra[0]['valor']

0.37

In [158]:
muestra[['codigo', 'valor']]

array([(b'ALFA', 0.37), (b'BETA', 0.11), (b'TAU', 0.13), (b'ALFA', 0.37),
       (b'ALFA', 0.11), (b'TAU', 0.13)],
      dtype={'names':['codigo','valor'], 'formats':['S4','<f8'], 'offsets':[0,12], 'itemsize':20})

In [159]:
#Todos los que tienen codigo ALFA
muestra[muestra['codigo'] == 'ALFA']

array([], shape=(0, 6),
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

### Broadcasting

In [160]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [161]:
x + 3

array([3, 4, 5, 6])

In [162]:
a = np.arange(12).reshape((3,4))
print(a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
b = np.array([1,2,3])
print(b.shape)
b

(3,)


array([1, 2, 3])

In [164]:
a + b
#Los indices y tamaños no coinciden, por lo que no puede realizar la operacion 

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [165]:
#Se acota el tamaño
b = b[:, np.newaxis]
print (b.shape)
b

(3, 1)


array([[1],
       [2],
       [3]])

In [166]:
a + b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [167]:
x = np.zeros((3,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [168]:
y = np.zeros(8)

In [169]:
#Operacion donde no coinciden las dimensiones
x + y

ValueError: operands could not be broadcast together with shapes (3,5) (8,) 

In [170]:
#Agrega una columna de ceros al final
x[..., None]

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [171]:
z = (x[..., None] + y)
print(z.shape)
z

(3, 5, 8)


array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])